const profitData = [
    {"shop":"Player","type":"Crop - Veggie","item":"Caroot","cost":"5","value":"14","farming":"Y","processing":"","foraging":"","others":"","profit":"9"},
    {"shop":"Player","type":"Crop - Veggie","item":"Cellulettuce","cost":"45","value":"100","farming":"Y","processing":"","foraging":"","others":"","profit":"55"},
    {"shop":"Player","type":"Crop - Veggie","item":"Lopauliflower","cost":"5","value":"48","farming":"Y","processing":"","foraging":"","others":"","profit":"43"},
    {"shop":"Player","type":"Crop - Veggie","item":"Sweetiebeetie","cost":"5","value":"22","farming":"Y","processing":"","foraging":"","others":"","profit":"17"},
    {"shop":"Player","type":"Crop - Veggie\/Mamoonia","item":"Sparkflower","cost":"5","value":"40","farming":"Y","processing":"","foraging":"","others":"","profit":"35"},
    {"shop":"Player","type":"Crop - Veggie\/Mamoonia","item":"Fartichoke","cost":"8","value":"60","farming":"Y","processing":"","foraging":"","others":"","profit":"52"},
    {"shop":"Player","type":"Crop - Fruity\/Nullwhere","item":"Dregplant","cost":"40","value":"320","farming":"Y","processing":"","foraging":"","others":"","profit":"280"},
    {"shop":"Player","type":"Crop - Fruity\/Nullwhere","item":"Freep","cost":"4","value":"24","farming":"Y","processing":"","foraging":"","others":"","profit":"20"},
    {"shop":"Player","type":"Crop - Fruity\/Nullwhere","item":"Hyperglob","cost":"40","value":"360","farming":"Y","processing":"","foraging":"","others":"","profit":"320"},
    {"shop":"Player","type":"Crop - Fruity","item":"Flootiflower","cost":"1.75","value":"10","farming":"Y","processing":"","foraging":"","others":"","profit":"8.25"},
    {"shop":"Player","type":"Crop - Fruity","item":"Pompadoot","cost":"8","value":"52","farming":"Y","processing":"","foraging":"","others":"","profit":"44"},
    {"shop":"Player","type":"Crop - Fruity","item":"Zinooka","cost":"3.33","value":"18","farming":"Y","processing":"","foraging":"","others":"","profit":"14.67"},
    {"shop":"Player","type":"Crop - No Event","item":"Bubblesprout","cost":"20","value":"111","farming":"Y","processing":"","foraging":"","others":"","profit":"91"},
    {"shop":"Player","type":"Crop - No Event","item":"Muz","cost":"3","value":"7","farming":"Y","processing":"","foraging":"","others":"","profit":"4"},
    {"shop":"Player","type":"Crop - No Event","item":"Springbean","cost":"2","value":"8","farming":"Y","processing":"","foraging":"","others":"","profit":"6"},
    {"shop":"Player","type":"Crop - No Event","item":"Thimbi","cost":"12.5","value":"79","farming":"Y","processing":"","foraging":"","others":"","profit":"66.5"},
    {"shop":"Player","type":"Crop - Processed","item":"Flooti Sauce","cost":"1.75","value":"12","farming":"Y","processing":"Y","foraging":"","others":"","profit":"10.25"},
    {"shop":"Player","type":"Crop - Processed","item":"Froobtose","cost":"5","value":"30","farming":"Y","processing":"Y","foraging":"","others":"","profit":"25"},
    {"shop":"Player","type":"Crop - Processed","item":"Ground Springbeans","cost":"2","value":"16","farming":"Y","processing":"Y","foraging":"","others":"","profit":"14"},
    {"shop":"Player","type":"Crop - Processed","item":"Muz Flour","cost":"3","value":"12","farming":"Y","processing":"Y","foraging":"","others":"","profit":"9"},
    {"shop":"Player","type":"Crop - Processed","item":"Pompadoot Juice","cost":"8","value":"64","farming":"Y","processing":"Y","foraging":"","others":"","profit":"56"},
    {"shop":"Player","type":"Food - Cake","item":"Caroot Cake","cost":"23","value":"134","farming":"Y","processing":"Y","foraging":"","others":"","profit":"111"},
    {"shop":"Player","type":"Food - Cake","item":"Go Go Cupcake","cost":"17.25","value":"200","farming":"Y","processing":"Y","foraging":"","others":"","profit":"182.75"},
    {"shop":"Player","type":"Food - Cake","item":"Pibblepug Pie","cost":"13","value":"142","farming":"Y","processing":"Y","foraging":"","others":"","profit":"129"},
    {"shop":"Player","type":"Food - Cake","item":"Quib Tart","cost":"5","value":"60","farming":"Y","processing":"Y","foraging":"Y","others":"","profit":"55"},
    {"shop":"Player","type":"Food - Cake","item":"Zinooka Cake","cost":"39.25","value":"400","farming":"Y","processing":"Y","foraging":"Y","others":"","profit":"360.75"},
    {"shop":"Player","type":"Food - Plates and Bowls","item":"Button Soup","cost":"10","value":"80","farming":"Y","processing":"","foraging":"Y","others":"","profit":"70"},
    {"shop":"Player","type":"Food - Plates and Bowls","item":"Clambrosia","cost":"5","value":"40","farming":"Y","processing":"","foraging":"Y","others":"","profit":"35"},
    {"shop":"Player","type":"Food - Plates and Bowls","item":"Creamadroostral Soup","cost":"16","value":"480","farming":"Y","processing":"Y","foraging":"Y","others":"","profit":"464"},
    {"shop":"Player","type":"Food - Plates and Bowls","item":"Glob Blobs","cost":"48","value":"500","farming":"Y","processing":"Y","foraging":"","others":"","profit":"452"},
    {"shop":"Player","type":"Food - Plates and Bowls","item":"Muzimi","cost":"7.75","value":"40","farming":"Y","processing":"","foraging":"Y","others":"","profit":"32.25"},
    {"shop":"Player","type":"Food - Plates and Bowls","item":"Oodles","cost":"3","value":"48","farming":"Y","processing":"","foraging":"Y","others":"","profit":"45"},
    {"shop":"Player","type":"Food - Plates and Bowls","item":"Pneumatic Gnocchi","cost":"3","value":"200","farming":"Y","processing":"Y","foraging":"Y","others":"","profit":"197"},
    {"shop":"Player","type":"Food - Plates and Bowls","item":"Roast Dregs","cost":"50.25","value":"498","farming":"Y","processing":"","foraging":"","others":"","profit":"447.75"},
    {"shop":"Player","type":"Food - Plates and Bowls","item":"Thimbi Tartare","cost":"40.5","value":"400","farming":"Y","processing":"Y","foraging":"Y","others":"","profit":"359.5"},
    {"shop":"Player","type":"Food - Sandwich","item":"A Very Cellulettuce Sammy","cost":"55","value":"200","farming":"Y","processing":"Y","foraging":"","others":"","profit":"145"},
    {"shop":"Player","type":"Food - Sandwich","item":"Bread Sammy","cost":"14","value":"80","farming":"Y","processing":"Y","foraging":"","others":"","profit":"66"},
    {"shop":"Player","type":"Food - Sandwich","item":"Gloom Bun","cost":"29","value":"240","farming":"Y","processing":"Y","foraging":"Y","others":"","profit":"211"},
    {"shop":"Player","type":"Food - Sandwich","item":"Hop Dob","cost":"8","value":"36","farming":"Y","processing":"Y","foraging":"","others":"","profit":"28"},
    {"shop":"Player","type":"Food - Sandwich","item":"Hop Hop Hop Dob","cost":"3","value":"220","farming":"Y","processing":"Y","foraging":"Y","others":"","profit":"217"},
    {"shop":"Player","type":"Food - Sandwich","item":"Squishmallow","cost":"80","value":"600","farming":"Y","processing":"Y","foraging":"","others":"","profit":"520"},
    {"shop":"Player","type":"Food - No Event","item":"Beebun","cost":"11","value":"115","farming":"Y","processing":"Y","foraging":"Y","others":"","profit":"104"},
    {"shop":"Player","type":"Food - No Event","item":"Beetie Curd","cost":"8","value":"39","farming":"Y","processing":"Y","foraging":"","others":"","profit":"31"},
    {"shop":"Player","type":"Food - No Event","item":"Blue Goo Pie","cost":"18","value":"159","farming":"Y","processing":"Y","foraging":"","others":"","profit":"141"},
    {"shop":"Player","type":"Food - No Event","item":"Candy Salad","cost":"5","value":"72","farming":"Y","processing":"Y","foraging":"Y","others":"","profit":"67"},
    {"shop":"Player","type":"Food - No Event","item":"Delislush","cost":"11.5","value":"287","farming":"Y","processing":"Y","foraging":"Y","others":"","profit":"275.5"},
    {"shop":"Player","type":"Food - No Event","item":"Flooti Karioka","cost":"8.5","value":"43","farming":"Y","processing":"Y","foraging":"","others":"","profit":"34.5"},
    {"shop":"Player","type":"Food - No Event","item":"Mamoonia Macaroon","cost":"21","value":"223","farming":"Y","processing":"Y","foraging":"","others":"","profit":"202"},
    {"shop":"Player","type":"Food - No Event","item":"Soggy Bread","cost":"14","value":"217","farming":"Y","processing":"Y","foraging":"Y","others":"","profit":"203"},
    {"shop":"Player","type":"Drinks","item":"Beanjuice","cost":"2","value":"30","farming":"Y","processing":"Y","foraging":"","others":"","profit":"28"},
    {"shop":"Player","type":"Drinks","item":"Lurge Latty","cost":"12","value":"240","farming":"Y","processing":"Y","foraging":"","others":"","profit":"228"},
    {"shop":"Player","type":"Drinks","item":"Sootheysip","cost":"0","value":"400","farming":"","processing":"","foraging":"Y","others":"","profit":"400"},
    {"shop":"Player","type":"Drinks","item":"Spressy","cost":"9","value":"80","farming":"Y","processing":"Y","foraging":"","others":"","profit":"71"},
    {"shop":"Player","type":"Foragables - Town","item":"Boregus","cost":"0","value":"24","farming":"","processing":"","foraging":"Y","others":"","profit":"24"},
    {"shop":"Player","type":"Foragables - Town","item":"Buttonboy","cost":"0","value":"4","farming":"","processing":"","foraging":"Y","others":"","profit":"4"},
    {"shop":"Player","type":"Foragables - Town","item":"Crumberry","cost":"0","value":"4","farming":"","processing":"","foraging":"Y","others":"","profit":"4"},
    {"shop":"Player","type":"Foragables - Town","item":"Curlyhorn","cost":"0","value":"200","farming":"","processing":"","foraging":"Y","others":"","profit":"200"},
    {"shop":"Player","type":"Foragables - Town","item":"Gastroglob","cost":"0","value":"2","farming":"","processing":"","foraging":"Y","others":"","profit":"2"},
    {"shop":"Player","type":"Foragables - Town","item":"Quib","cost":"0","value":"2","farming":"","processing":"","foraging":"Y","others":"","profit":"2"},
    {"shop":"Player","type":"Foragables - Town","item":"Seaplop","cost":"0","value":"12","farming":"","processing":"","foraging":"Y","others":"","profit":"12"},
    {"shop":"Player","type":"Foragables - Town","item":"Shelbo","cost":"0","value":"6","farming":"","processing":"","foraging":"Y","others":"","profit":"6"},
    {"shop":"Player","type":"Foragables - Town","item":"Sporbet","cost":"0","value":"6","farming":"","processing":"","foraging":"Y","others":"","profit":"6"},
    {"shop":"Player","type":"Foragables - Region\/Mamoonia","item":"Balmybloom","cost":"0","value":"40","farming":"","processing":"","foraging":"Y","others":"","profit":"40"},
    {"shop":"Player","type":"Foragables - Region","item":"Bunch-o-buttons","cost":"0","value":"6","farming":"","processing":"","foraging":"Y","others":"","profit":"6"},
    {"shop":"Player","type":"Foragables - Region","item":"Gember","cost":"0","value":"160","farming":"","processing":"","foraging":"Y","others":"","profit":"160"},
    {"shop":"Player","type":"Foragables - Region","item":"Droostral","cost":"0","value":"160","farming":"","processing":"","foraging":"Y","others":"","profit":"160"},
    {"shop":"Player","type":"Foragables - Region","item":"Sprockut","cost":"0","value":"160","farming":"","processing":"","foraging":"Y","others":"","profit":"160"},
    {"shop":"Player","type":"Foragables - No Event","item":"Honeygob","cost":"0","value":"2","farming":"","processing":"","foraging":"Y","others":"","profit":"2"},
    {"shop":"Player","type":"Foragables - No Event","item":"Rainplop","cost":"0","value":"127","farming":"","processing":"","foraging":"Y","others":"","profit":"127"},
    {"shop":"Player","type":"Foragables - No Event","item":"Snowplop","cost":"0","value":"57","farming":"","processing":"","foraging":"Y","others":"","profit":"57"},
    {"shop":"Player","type":"Foragables - No Event","item":"Spicyspear","cost":"0","value":"127","farming":"","processing":"","foraging":"Y","others":"","profit":"127"},
    {"shop":"Player","type":"Sea Dangling","item":"Soggy Balloon","cost":"0","value":"10","farming":"","processing":"","foraging":"","others":"Y","profit":"10"},
    {"shop":"Player","type":"Sea Dangling","item":"Gross Boot","cost":"0","value":"50","farming":"","processing":"","foraging":"","others":"Y","profit":"50"},
    {"shop":"Player","type":"Sea Dangling","item":"Shiny Bait","cost":"0","value":"50","farming":"","processing":"","foraging":"","others":"Y","profit":"50"},
    {"shop":"Player","type":"Sea Dangling","item":"Wrapper","cost":"0","value":"50","farming":"","processing":"","foraging":"","others":"Y","profit":"50"},
    {"shop":"Player","type":"Sea Dangling","item":"Pop Top","cost":"0","value":"50","farming":"","processing":"","foraging":"","others":"Y","profit":"50"},
    {"shop":"Player","type":"Sea Dangling","item":"Super Bait","cost":"0","value":"64","farming":"","processing":"","foraging":"","others":"Y","profit":"64"},
    {"shop":"Player","type":"Sea Dangling","item":"Basic Bait","cost":"0","value":"64","farming":"","processing":"","foraging":"","others":"Y","profit":"64"},
    {"shop":"Player","type":"Sea Dangling","item":"High Quality Bait","cost":"0","value":"64","farming":"","processing":"","foraging":"","others":"Y","profit":"64"},
    {"shop":"Player","type":"Sea Dangling","item":"Meltilizer","cost":"0","value":"64","farming":"","processing":"","foraging":"","others":"Y","profit":"64"},
    {"shop":"Player","type":"Sea Dangling","item":"Speedy Grow","cost":"0","value":"64","farming":"","processing":"","foraging":"","others":"Y","profit":"64"},
    {"shop":"Player","type":"Sea Dangling","item":"Speedy Grow Pro","cost":"0","value":"64","farming":"","processing":"","foraging":"","others":"Y","profit":"64"},
    {"shop":"Player","type":"Sea Dangling","item":"Stay Soggy","cost":"0","value":"64","farming":"","processing":"","foraging":"","others":"Y","profit":"64"},
    {"shop":"Player","type":"Sea Dangling","item":"Stay Soggy Extra Sog","cost":"0","value":"64","farming":"","processing":"","foraging":"","others":"Y","profit":"64"},
    {"shop":"Player","type":"Building","item":"Clothlet","cost":"32","value":"20","farming":"Y","processing":"","foraging":"","others":"","profit":"-12"},
    {"shop":"Player","type":"Building","item":"Nurny","cost":"0","value":"4","farming":"","processing":"","foraging":"","others":"Y","profit":"4"},
    {"shop":"Player","type":"Building","item":"Oobsidian","cost":"0","value":"160","farming":"","processing":"","foraging":"","others":"Y","profit":"160"},
    {"shop":"Player","type":"Building","item":"Planklet","cost":"0","value":"6","farming":"","processing":"","foraging":"","others":"Y","profit":"6"},
    {"shop":"Player","type":"Ooblet Figurine","item":"Average Figurine","cost":"0","value":"60","farming":"","processing":"","foraging":"","others":"Y","profit":"60"},
    {"shop":"Player","type":"Others - No Event","item":"Balloon","cost":"0","value":"108","farming":"","processing":"","foraging":"","others":"Y","profit":"108"},
    {"shop":"Player","type":"Others - No Event","item":"Bulk Candy","cost":"0","value":"14","farming":"","processing":"","foraging":"","others":"Y","profit":"14"},
    {"shop":"Player","type":"Others - No Event","item":"Bunglebee Bun","cost":"40","value":"28","farming":"","processing":"","foraging":"","others":"Y","profit":"-12"},
    {"shop":"Player","type":"Others - No Event","item":"Candy","cost":"0","value":"115","farming":"","processing":"","foraging":"","others":"Y","profit":"115"},
    {"shop":"Player","type":"Others - No Event","item":"Essence of Embiggening","cost":"0","value":"115","farming":"","processing":"","foraging":"","others":"Y","profit":"115"},
    {"shop":"Player","type":"Others - No Event","item":"Festive Bobble","cost":"0","value":"14","farming":"","processing":"","foraging":"","others":"Y","profit":"14"},
    {"shop":"Player","type":"Others - No Event","item":"Flooti Flour","cost":"0","value":"26","farming":"","processing":"","foraging":"","others":"Y","profit":"26"},
    {"shop":"Player","type":"Others - No Event","item":"Jinglebread Oob Cookie","cost":"0","value":"28","farming":"","processing":"","foraging":"","others":"Y","profit":"28"},
    {"shop":"Player","type":"Others - No Event","item":"Mystery Can","cost":"0","value":"5","farming":"","processing":"","foraging":"","others":"Y","profit":"5"},
    {"shop":"Player","type":"Others - No Event","item":"Quabbo Balloon","cost":"0","value":"181","farming":"","processing":"","foraging":"","others":"Y","profit":"181"},
    {"shop":"Player","type":"Others - No Event","item":"Tincture of Tinying","cost":"0","value":"115","farming":"","processing":"","foraging":"","others":"Y","profit":"115"},
    {"shop":"Player","type":"Ooblet Glasses","item":"Bandaid","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Player","type":"Ooblet Glasses","item":"Eyeball Enhancers","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Glasses","item":"Eyeball Glasses","cost":"0","value":"100","farming":"","processing":"","foraging":"","others":"Y","profit":"100"},
    {"shop":"Player","type":"Ooblet Glasses","item":"Green Sunglasses","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Player","type":"Ooblet Glasses","item":"Hay Twig","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Glasses","item":"Hypno Glasses","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Glasses","item":"Jazzy Glasses","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Glasses","item":"Lil Mask","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Glasses","item":"Monocle","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Glasses","item":"Panache Glasses","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Glasses","item":"Sunglasses","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Hats","item":"Antlers 1","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Hats","item":"Antlers 2","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Hats","item":"Baby Present Costume","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Hats","item":"Baby Pumpkin Costume","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Hats","item":"Baby Snowplop Costume","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Hats","item":"Baby Warm Hat","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Hats","item":"Baby Wizard Hat","cost":"0","value":"20","farming":"","processing":"","foraging":"","others":"Y","profit":"20"},
    {"shop":"Player","type":"Ooblet Hats","item":"Beanie","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Player","type":"Ooblet Hats","item":"Bowler Hat","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Player","type":"Ooblet Hats","item":"Feather Hat","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Player","type":"Ooblet Hats","item":"Fluffy Hat 1","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Hats","item":"Fluffy Hat 2","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Hats","item":"Head Flower","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Player","type":"Ooblet Hats","item":"Headband","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Player","type":"Ooblet Hats","item":"Lil Hard Hat","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Hats","item":"Little Beret","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Player","type":"Ooblet Hats","item":"Official Police Hat","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Hats","item":"Party Hat","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Hats","item":"Pirate Hat","cost":"0","value":"250","farming":"","processing":"","foraging":"","others":"Y","profit":"250"},
    {"shop":"Player","type":"Ooblet Hats","item":"Propella Hat","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Hats","item":"Rain Hat","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Player","type":"Ooblet Hats","item":"Safari Hat","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Hats","item":"Sailorin Hat","cost":"0","value":"250","farming":"","processing":"","foraging":"","others":"Y","profit":"250"},
    {"shop":"Player","type":"Ooblet Hats","item":"Spriggle Top","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Hats","item":"Tall Crown","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Hats","item":"Top Hat","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Player","type":"Ooblet Hats","item":"Witchy Hat","cost":"0","value":"80","farming":"","processing":"","foraging":"","others":"Y","profit":"80"},
    {"shop":"Player","type":"Ooblet Necks","item":"Baby Cape","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Necks","item":"Backpacky","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Player","type":"Ooblet Necks","item":"Bow Tie (Blue)","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Necks","item":"Bow Tie (Dotted Black)","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Player","type":"Ooblet Necks","item":"Bow Tie (Pink)","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Player","type":"Ooblet Necks","item":"Bow Tie (Striped Red)","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Player","type":"Ooblet Necks","item":"Fannypack","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Player","type":"Ooblet Necks","item":"Lil Spooky Wings","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Necks","item":"Ruff","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Player","type":"Ooblet Necks","item":"Tutu","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Player","type":"Ooblet Shoes","item":"Baby Skates","cost":"0","value":"150","farming":"","processing":"","foraging":"","others":"Y","profit":"150"},
    {"shop":"Player","type":"Ooblet Wands","item":"Bat","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Player","type":"Ooblet Wands","item":"Blue Chalk","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Wands","item":"Camby Cane","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Wands","item":"Green Chalk","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Wands","item":"Handbag","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Wands","item":"Ice Cream Cone","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Player","type":"Ooblet Wands","item":"Lollipop","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Player","type":"Ooblet Wands","item":"Love You Wand","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Player","type":"Ooblet Wands","item":"Popsicle","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Player","type":"Ooblet Wands","item":"Propella Umbrella","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Player","type":"Ooblet Wands","item":"Red Chalk","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Wands","item":"Sand Shovel","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Wands","item":"Sophisticated Umbrella","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Wands","item":"Star Umbrella","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Wands","item":"Transmitter","cost":"0","value":"16","farming":"","processing":"","foraging":"","others":"Y","profit":"16"},
    {"shop":"Player","type":"Ooblet Wands","item":"Water Pistol","cost":"0","value":"320","farming":"","processing":"","foraging":"","others":"Y","profit":"320"},
    {"shop":"Plenny","type":"1","item":"Caroot","cost":"5","value":"9.1","farming":"Y","processing":"","foraging":"","profit":"4.1"},
    {"shop":"Plenny","type":"1","item":"Clothlets","cost":"32","value":"13","farming":"Y","processing":"","foraging":"","profit":"-19"},
    {"shop":"Plenny","type":"1","item":"Muz","cost":"3","value":"6.5","farming":"Y","processing":"","foraging":"","profit":"3.5"},
    {"shop":"Plenny","type":"1","item":"Nurnies","cost":"0","value":"2.6","farming":"","processing":"","foraging":"","profit":"2.6"},
    {"shop":"Plenny","type":"1","item":"Planklets","cost":"0","value":"3.9","farming":"","processing":"","foraging":"","profit":"3.9"},
    {"shop":"Plenny","type":"1","item":"Sweetiebeeties","cost":"5","value":"14.3","farming":"Y","processing":"","foraging":"","profit":"9.3"},
    {"shop":"Plenny","type":"2","item":"Flootiflowers","cost":"1.75","value":"8","farming":"Y","processing":"","foraging":"","profit":"6.25"},
    {"shop":"Plenny","type":"2","item":"Froobtose","cost":"5","value":"24","farming":"Y","processing":"Y","foraging":"","profit":"19"},
    {"shop":"Plenny","type":"2","item":"Ground Springbeans","cost":"2","value":"12.8","farming":"Y","processing":"Y","foraging":"","profit":"10.8"},
    {"shop":"Plenny","type":"2","item":"Lopauliflowers","cost":"5","value":"38.4","farming":"Y","processing":"","foraging":"","profit":"33.4"},
    {"shop":"Plenny","type":"2","item":"Muz Flour","cost":"3","value":"9.6","farming":"Y","processing":"Y","foraging":"","profit":"6.6"},
    {"shop":"Plenny","type":"2","item":"Pompadoots","cost":"8","value":"41.6","farming":"Y","processing":"","foraging":"","profit":"33.6"},
    {"shop":"Plenny","type":"2","item":"Springbeans","cost":"2","value":"9.6","farming":"Y","processing":"","foraging":"","profit":"7.6"},
    {"shop":"Plenny","type":"2","item":"Zinookas","cost":"3.33","value":"14.4","farming":"Y","processing":"","foraging":"","profit":"11.07"},
    {"shop":"Plenny","type":"3","item":"Beanjuice","cost":"2","value":"30","farming":"Y","processing":"Y","foraging":"","profit":"28"},
    {"shop":"Plenny","type":"3","item":"Beetie Curd","cost":"8","value":"50","farming":"Y","processing":"Y","foraging":"","profit":"42"},
    {"shop":"Plenny","type":"3","item":"Clambrosia","cost":"5","value":"40","farming":"Y","processing":"","foraging":"Y","profit":"35"},
    {"shop":"Plenny","type":"3","item":"Fartichokes","cost":"8","value":"60","farming":"Y","processing":"","foraging":"","profit":"52"},
    {"shop":"Plenny","type":"3","item":"Flooti Kariokas","cost":"8.5","value":"60","farming":"Y","processing":"Y","foraging":"","profit":"51.5"},
    {"shop":"Plenny","type":"3","item":"Hop Dobs","cost":"3","value":"36","farming":"Y","processing":"Y","foraging":"Y","profit":"33"},
    {"shop":"Plenny","type":"3","item":"Muzimi","cost":"7.75","value":"40","farming":"Y","processing":"","foraging":"Y","profit":"32.25"},
    {"shop":"Plenny","type":"3","item":"Oodles","cost":"3","value":"48","farming":"Y","processing":"","foraging":"Y","profit":"45"},
    {"shop":"Plenny","type":"3","item":"Pompadoot Juice","cost":"8","value":"64","farming":"Y","processing":"Y","foraging":"","profit":"56"},
    {"shop":"Plenny","type":"3","item":"Sparkflowers","cost":"5","value":"40","farming":"Y","processing":"","foraging":"","profit":"35"},
    {"shop":"Plenny","type":"4","item":"Blue Goo Pie","cost":"18","value":"240","farming":"Y","processing":"Y","foraging":"","profit":"222"},
    {"shop":"Plenny","type":"4","item":"Go Go Cupcakes","cost":"17.25","value":"240","farming":"Y","processing":"Y","foraging":"","profit":"222.75"},
    {"shop":"Plenny","type":"4","item":"Hop Hop Hop Dobs","cost":"3","value":"264","farming":"Y","processing":"Y","foraging":"Y","profit":"261"},
    {"shop":"Plenny","type":"4","item":"Lurge Lattys","cost":"12","value":"288","farming":"Y","processing":"Y","foraging":"","profit":"276"},
    {"shop":"Plenny","type":"4","item":"Pibblepug Pies","cost":"13","value":"170.4","farming":"Y","processing":"Y","foraging":"","profit":"157.4"},
    {"shop":"Plenny","type":"4","item":"Spressies","cost":"9","value":"96","farming":"Y","processing":"Y","foraging":"","profit":"87"},
    {"shop":"Plenny","type":"4","item":"Zinooka Cake","cost":"18","value":"480","farming":"Y","processing":"Y","foraging":"","profit":"462"},
    {"shop":"Plenny","type":"1+","item":"Borguses","cost":"0","value":"16.8","farming":"","processing":"","foraging":"Y","profit":"16.8"},
    {"shop":"Plenny","type":"1+","item":"Buttonboys","cost":"0","value":"2.8","farming":"","processing":"","foraging":"Y","profit":"2.8"},
    {"shop":"Plenny","type":"1+","item":"Muz","cost":"3","value":"7","farming":"Y","processing":"","foraging":"","profit":"4"},
    {"shop":"Plenny","type":"1+","item":"Nurnies","cost":"0","value":"2.8","farming":"","processing":"","foraging":"Y","profit":"2.8"},
    {"shop":"Plenny","type":"1+","item":"Planklets","cost":"0","value":"4.2","farming":"","processing":"","foraging":"Y","profit":"4.2"},
    {"shop":"Plenny","type":"1+","item":"Quibs","cost":"0","value":"1.4","farming":"","processing":"","foraging":"Y","profit":"1.4"},
    {"shop":"Plenny","type":"1+","item":"Seaplops","cost":"0","value":"8.4","farming":"","processing":"","foraging":"Y","profit":"8.4"},
    {"shop":"Plenny","type":"1+","item":"Shelbos","cost":"0","value":"4.2","farming":"","processing":"","foraging":"Y","profit":"4.2"},
    {"shop":"Plenny","type":"1+","item":"Sporbets","cost":"0","value":"4.2","farming":"","processing":"","foraging":"Y","profit":"4.2"},
    {"shop":"Plenny","type":"2+","item":"Bread Sammy","cost":"14","value":"72","farming":"Y","processing":"Y","foraging":"","profit":"58"},
    {"shop":"Plenny","type":"2+","item":"Bubblesprouts","cost":"20","value":"126","farming":"Y","processing":"","foraging":"","profit":"106"},
    {"shop":"Plenny","type":"2+","item":"Cellulettuces","cost":"45","value":"90","farming":"Y","processing":"","foraging":"","profit":"45"},
    {"shop":"Plenny","type":"2+","item":"Curlyhorns","cost":"0","value":"180","farming":"","processing":"","foraging":"Y","profit":"180"},
    {"shop":"Plenny","type":"2+","item":"Dregplants","cost":"40","value":"288","farming":"Y","processing":"","foraging":"","profit":"248"},
    {"shop":"Plenny","type":"2+","item":"Freeps","cost":"4","value":"21.6","farming":"Y","processing":"","foraging":"","profit":"17.6"},
    {"shop":"Plenny","type":"2+","item":"Hyperglobs","cost":"40","value":"324","farming":"Y","processing":"","foraging":"","profit":"284"},
    {"shop":"Plenny","type":"2+","item":"Quib Tarts","cost":"5","value":"54","farming":"Y","processing":"Y","foraging":"Y","profit":"49"},
    {"shop":"Plenny","type":"2+","item":"Sootheysip","cost":"0","value":"360","farming":"","processing":"","foraging":"Y","profit":"360"},
    {"shop":"Plenny","type":"2+","item":"Thimbis","cost":"12.5","value":"99","farming":"Y","processing":"","foraging":"","profit":"86.5"},
    {"shop":"Plenny","type":"3+","item":"Candy Salad","cost":"5","value":"110","farming":"Y","processing":"Y","foraging":"Y","profit":"105"},
    {"shop":"Plenny","type":"3+","item":"Droostrals","cost":"0","value":"176","farming":"","processing":"","foraging":"Y","profit":"176"},
    {"shop":"Plenny","type":"3+","item":"Glob Blobs","cost":"48","value":"550","farming":"Y","processing":"Y","foraging":"","profit":"502"},
    {"shop":"Plenny","type":"3+","item":"Gloom Bun","cost":"29","value":"264","farming":"Y","processing":"Y","foraging":"Y","profit":"235"},
    {"shop":"Plenny","type":"3+","item":"Mamoonia Macaroon","cost":"21","value":"308","farming":"Y","processing":"Y","foraging":"","profit":"287"},
    {"shop":"Plenny","type":"3+","item":"Pneumatic Gnocchi","cost":"3","value":"220","farming":"Y","processing":"Y","foraging":"Y","profit":"217"},
    {"shop":"Plenny","type":"3+","item":"Roast Dregs","cost":"5.25","value":"547.8","farming":"Y","processing":"","foraging":"","profit":"542.55"},
    {"shop":"Plenny","type":"3+","item":"Thimbi Tartare","cost":"40.5","value":"440","farming":"Y","processing":"Y","foraging":"Y","profit":"399.5"},
    {"shop":"Plenny","type":"4+","item":"A Very Cellulettuce Sammy","cost":"55","value":"260","farming":"Y","processing":"Y","foraging":"","profit":"205"},
    {"shop":"Plenny","type":"4+","item":"Button Soups","cost":"10","value":"104","farming":"Y","processing":"","foraging":"Y","profit":"94"},
    {"shop":"Plenny","type":"4+","item":"Creamadroostral Soups","cost":"16","value":"624","farming":"Y","processing":"Y","foraging":"Y","profit":"608"},
    {"shop":"Plenny","type":"4+","item":"Delislushes","cost":"11.5","value":"468","farming":"Y","processing":"Y","foraging":"Y","profit":"456.5"},
    {"shop":"Plenny","type":"4+","item":"Oobsidian","cost":"0","value":"208","farming":"","processing":"","foraging":"","profit":"208"},
    {"shop":"Plenny","type":"4+","item":"Soggy Bread","cost":"14","value":"390","farming":"Y","processing":"Y","foraging":"Y","profit":"376"},
    {"shop":"Plenny","type":"4+","item":"Squishmallow","cost":"80","value":"780","farming":"Y","processing":"Y","foraging":"","profit":"700"},
    {"shop":"Meed","type":"Crop","item":"Caroot","cost":"5","value":"7","farming":"Y","processing":"","foraging":"","profit":"2"},
    {"shop":"Meed","type":"Crop","item":"Cellulettuce","cost":"45","value":"50","farming":"Y","processing":"","foraging":"","profit":"5"},
    {"shop":"Meed","type":"Crop","item":"Lopauliflower","cost":"5","value":"24","farming":"Y","processing":"","foraging":"","profit":"19"},
    {"shop":"Meed","type":"Crop","item":"Sweetiebeetie","cost":"5","value":"11","farming":"Y","processing":"","foraging":"","profit":"6"},
    {"shop":"Meed","type":"Crop","item":"Sparkflower","cost":"5","value":"20","farming":"Y","processing":"","foraging":"","profit":"15"},
    {"shop":"Meed","type":"Crop","item":"Fartichoke","cost":"8","value":"30","farming":"Y","processing":"","foraging":"","profit":"22"},
    {"shop":"Meed","type":"Crop","item":"Dregplant","cost":"40","value":"160","farming":"Y","processing":"","foraging":"","profit":"120"},
    {"shop":"Meed","type":"Crop","item":"Freep","cost":"4","value":"12","farming":"Y","processing":"","foraging":"","profit":"8"},
    {"shop":"Meed","type":"Crop","item":"Hyperglob","cost":"40","value":"180","farming":"Y","processing":"","foraging":"","profit":"140"},
    {"shop":"Meed","type":"Crop","item":"Flootiflower","cost":"1.75","value":"5","farming":"Y","processing":"","foraging":"","profit":"3.25"},
    {"shop":"Meed","type":"Crop","item":"Pompadoot","cost":"8","value":"26","farming":"Y","processing":"","foraging":"","profit":"18"},
    {"shop":"Meed","type":"Crop","item":"Zinooka","cost":"3.33","value":"9","farming":"Y","processing":"","foraging":"","profit":"5.67"},
    {"shop":"Meed","type":"Crop","item":"Bubblesprout","cost":"20","value":"70","farming":"Y","processing":"","foraging":"","profit":"50"},
    {"shop":"Meed","type":"Crop","item":"Muz","cost":"3","value":"5","farming":"Y","processing":"","foraging":"","profit":"2"},
    {"shop":"Meed","type":"Crop","item":"Springbean","cost":"2","value":"6","farming":"Y","processing":"","foraging":"","profit":"4"},
    {"shop":"Meed","type":"Crop","item":"Thimbi","cost":"12.5","value":"55","farming":"Y","processing":"","foraging":"","profit":"42.5"},
    {"shop":"Meed","type":"Crop","item":"Clothlet","cost":"32","value":"10","farming":"Y","processing":"","foraging":"","profit":"-22"},
    {"shop":"Meed","type":"Crop - Processed","item":"Froobtose","cost":"0","value":"15","farming":"Y","processing":"Y","foraging":"","profit":"15"},
    {"shop":"Meed","type":"Crop - Processed","item":"Muz Flour","cost":"0","value":"6","farming":"Y","processing":"Y","foraging":"","profit":"6"},
    {"shop":"Meed","type":"Foragables","item":"Boregus","cost":"0","value":"12","farming":"","processing":"","foraging":"Y","profit":"12"},
    {"shop":"Meed","type":"Foragables","item":"Buttonboy","cost":"0","value":"2","farming":"","processing":"","foraging":"Y","profit":"2"},
    {"shop":"Meed","type":"Foragables","item":"Crumberry","cost":"0","value":"2","farming":"","processing":"","foraging":"Y","profit":"2"},
    {"shop":"Meed","type":"Foragables","item":"Curlyhorn","cost":"0","value":"100","farming":"","processing":"","foraging":"Y","profit":"100"},
    {"shop":"Meed","type":"Foragables","item":"Gastroglob","cost":"0","value":"1","farming":"","processing":"","foraging":"Y","profit":"1"},
    {"shop":"Meed","type":"Foragables","item":"Quib","cost":"0","value":"1","farming":"","processing":"","foraging":"Y","profit":"1"},
    {"shop":"Meed","type":"Foragables","item":"Seaplop","cost":"0","value":"6","farming":"","processing":"","foraging":"Y","profit":"6"},
    {"shop":"Meed","type":"Foragables","item":"Shelbo","cost":"0","value":"3","farming":"","processing":"","foraging":"Y","profit":"3"},
    {"shop":"Meed","type":"Foragables","item":"Sporbet","cost":"0","value":"3","farming":"","processing":"","foraging":"Y","profit":"3"},
    {"shop":"Meed","type":"Foragables","item":"Honeygob","cost":"0","value":"2","farming":"","processing":"","foraging":"Y","profit":"2"},
    {"shop":"Meed","type":"Others","item":"Planklet","cost":"0","value":"3","farming":"","processing":"","foraging":"","profit":"3"},
    {"shop":"Cafe","type":"Crop","item":"Springbean","cost":"2","value":"9","farming":"Y","processing":"","foraging":"","profit":"7"},
    {"shop":"Cafe","type":"Crop - Processed","item":"Ground Springbeans","cost":"2","value":"8","farming":"Y","processing":"Y","foraging":"","profit":"6"},
    {"shop":"Cafe","type":"Crop - Processed","item":"Pompadoot Juice","cost":"8","value":"32","farming":"Y","processing":"Y","foraging":"","profit":"24"},
    {"shop":"Cafe","type":"Food","item":"Caroot Cake","cost":"23","value":"67","farming":"Y","processing":"Y","foraging":"","profit":"44"},
    {"shop":"Cafe","type":"Food","item":"Go Go Cupcake","cost":"17","value":"100","farming":"Y","processing":"Y","foraging":"","profit":"83"},
    {"shop":"Cafe","type":"Food","item":"Quib Tart","cost":"5","value":"30","farming":"Y","processing":"Y","foraging":"Y","profit":"25"},
    {"shop":"Cafe","type":"Food","item":"Zinooka Cake","cost":"39","value":"200","farming":"Y","processing":"Y","foraging":"Y","profit":"161"},
    {"shop":"Cafe","type":"Food","item":"Button Soup","cost":"10","value":"40","farming":"Y","processing":"","foraging":"Y","profit":"30"},
    {"shop":"Cafe","type":"Food","item":"Clambrosia","cost":"5","value":"20","farming":"Y","processing":"","foraging":"Y","profit":"15"},
    {"shop":"Cafe","type":"Food","item":"Creamadroostral Soup","cost":"16","value":"240","farming":"Y","processing":"Y","foraging":"Y","profit":"224"},
    {"shop":"Cafe","type":"Food","item":"Glob Blobs","cost":"48","value":"250","farming":"Y","processing":"Y","foraging":"","profit":"202"},
    {"shop":"Cafe","type":"Food","item":"Oodles","cost":"3","value":"24","farming":"Y","processing":"","foraging":"Y","profit":"21"},
    {"shop":"Cafe","type":"Food","item":"Pneumatic Gnocchi","cost":"3","value":"100","farming":"Y","processing":"Y","foraging":"Y","profit":"97"},
    {"shop":"Cafe","type":"Food","item":"Roast Dregs","cost":"50","value":"249","farming":"Y","processing":"","foraging":"","profit":"199"},
    {"shop":"Cafe","type":"Food","item":"Thimbi Tartare","cost":"41","value":"200","farming":"Y","processing":"Y","foraging":"Y","profit":"159"},
    {"shop":"Cafe","type":"Food","item":"A Very Cellulettuce Sammy","cost":"55","value":"100","farming":"Y","processing":"Y","foraging":"","profit":"45"},
    {"shop":"Cafe","type":"Food","item":"Bread Sammy","cost":"14","value":"40","farming":"Y","processing":"Y","foraging":"","profit":"26"},
    {"shop":"Cafe","type":"Food","item":"Gloom Bun","cost":"29","value":"120","farming":"Y","processing":"Y","foraging":"Y","profit":"91"},
    {"shop":"Cafe","type":"Food","item":"Hop Dob","cost":"8","value":"18","farming":"Y","processing":"Y","foraging":"","profit":"10"},
    {"shop":"Cafe","type":"Food","item":"Hop Hop Hop Dob","cost":"3","value":"110","farming":"Y","processing":"Y","foraging":"Y","profit":"107"},
    {"shop":"Cafe","type":"Food","item":"Beebun","cost":"11","value":"80","farming":"Y","processing":"Y","foraging":"Y","profit":"69"},
    {"shop":"Cafe","type":"Food","item":"Candy Salad","cost":"5","value":"50","farming":"Y","processing":"Y","foraging":"Y","profit":"45"},
    {"shop":"Cafe","type":"Food","item":"Delislush","cost":"12","value":"180","farming":"Y","processing":"Y","foraging":"Y","profit":"168"},
    {"shop":"Cafe","type":"Food","item":"Flooti Karioka","cost":"9","value":"30","farming":"Y","processing":"Y","foraging":"","profit":"21"},
    {"shop":"Cafe","type":"Food","item":"Soggy Bread","cost":"14","value":"150","farming":"Y","processing":"Y","foraging":"Y","profit":"136"},
    {"shop":"Cafe","type":"Drinks","item":"Beanjuice","cost":"2","value":"15","farming":"Y","processing":"Y","foraging":"","profit":"13"},
    {"shop":"Cafe","type":"Drinks","item":"Lurge Latty","cost":"12","value":"120","farming":"Y","processing":"Y","foraging":"","profit":"108"},
    {"shop":"Cafe","type":"Drinks","item":"Sootheysip","cost":"0","value":"200","farming":"","processing":"","foraging":"Y","profit":"200"},
    {"shop":"Cafe","type":"Drinks","item":"Spressy","cost":"9","value":"40","farming":"Y","processing":"Y","foraging":"","profit":"31"},
    {"shop":"Cafe","type":"Others","item":"Soggy Balloon","cost":"0","value":"5","farming":"","processing":"","foraging":"","profit":"5"},
    {"shop":"Cafe","type":"Others","item":"Bulk Candy","cost":"0","value":"10","farming":"","processing":"","foraging":"","profit":"10"},
    {"shop":"Cafe","type":"Others","item":"Jinglebread Oob Cookie","cost":"0","value":"20","farming":"","processing":"","foraging":"","profit":"20"}
];

profitData.forEach(item => {
   $('#profit-' + item.shop + ' tbody').append(
       $(document.createElement('tr'))
           .append(
               $(document.createElement('td'))
                   .addClass('profitToggleable')
                   .text(item.type)
           )
           .append(
               $(document.createElement('td'))
                   .text(item.item)
           )
           .append(
               $(document.createElement('td'))
                   .addClass('profitToggleable text-end')
                   .text(Math.round(item.cost))
           )
           .append(
               $(document.createElement('td'))
                   .addClass('profitToggleable text-end')
                   .text(Math.round(item.value))
           )
           .append(
               $(document.createElement('td'))
                   .addClass('text-center')
                   .append(
                       $(document.createElement('i'))
                           .addClass((item.farming === 'Y') ? 'fa-solid fa-seedling' : '')
                   )
           )
           .append(
               $(document.createElement('td'))
                   .addClass('text-center')
                   .append(
                       $(document.createElement('i'))
                           .addClass((item.processing === 'Y') ? 'fa-solid fa-mortar-pestle' : '')
                   )
           )
           .append(
               $(document.createElement('td'))
                   .addClass('text-center')
                   .append(
                       $(document.createElement('i'))
                           .addClass((item.foraging === 'Y') ? 'fa-solid fa-tree' : '')
                   )
           )
           .append(
               $(document.createElement('td'))
                   .addClass('text-end profit-totalProfit')
                   .text(Math.round(item.profit))
           )
           .append(
               $(document.createElement('td'))
                   .append(
                       $(document.createElement('div'))
                           .addClass('profit-profitBar og-bg-profitgreen')
                   )
           )
   )
});